the_end/the_end/urls.py
from django.contrib import admin
from django.urls import path,  include
from django.contrib.flatpages import views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('author/', views.flatpage, {'url': '/author/'}, name='about_me'),
    path('tech/', views.flatpage, {'url': '/tech/'}, name='tech'),
    path('foodgram/', views.flatpage, {'url': '/foodgram/'}, name='foodgram'),
    path("auth/", include("user.urls")),
    path("auth/", include("django.contrib.auth.urls")),
    path("", include("v1.urls")),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

the_end/v1/urls.py
from django.contrib import admin
from django.urls import path,  include
from . import views


urlpatterns = [
    path("ingredients", views.get_ingredients_js, name="get_ingredients"),
    path("recipe/new/", views.user_recipe_new, name="recipe_new"),
    path("recipe/<int:recipe_id>/edit/", views.user_recipe_edit, name="recipe_edit"),

    path("follow/", views.follow_index, name="follow_index"),
    path("author/<int:user_id>/",views.author_list, name="author"),

    path("recipe/<int:recipe_id>/", views.recipe_view, name="recipe_view"),
    # path("recipe/new/", views.recipe_create, name="recipe_new"),
    path("favorite/", views.favorite, name="favorites"),
    path("favorites", views.add_favorite, name="add_favorite"),
    # path("favorites/", views.add_favorite, name="add_favorite"),
    path("favorites/<int:recipe_id>",
         views.delete_favorite, name="delete_favorite"),

    path("subscriptions", views.add_subscription, name="add_subscription"),
    path("subscriptions/", views.add_subscription, name="add_subscription"),
    path("subscriptions/<int:following_id>",
         views.delete_subscription, name="delete_subscription"),

    path("purchases", views.add_purchases, name="add_purchases"),
    path("purchases/", views.add_purchases, name="add_purchases"),
    path("purchases/<int:recipe_id>",
         views.delete_purchases, name="delete_purchases"),
    path("purchases/<int:recipe_id>/",
         views.delete_purchases, name="delete_purchases"),

    path('shopping-list/', views.shopping_list, name='shopping-list'),

    path("", views.index, name="index"),
]

the_end/v1/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()

class Ingredient(models.Model):
    """
    Информация об ингредиенте
    """
    name = models.CharField(max_length=100, verbose_name='Название')
    description = models.CharField(max_length=1000, verbose_name='Описание')

    measurement = (
        ('шт', 'шт'),
        ('г', 'г'),
        ('ст.л', 'ст.л'),
        ('ч.л', 'ч.л'),
        ('мл','мл')
    )

    units_of_measurement = models.CharField(choices=measurement, max_length=20, verbose_name='Единицы измерения')

    def __str__(self):
        return f'{self.name} ({self.units_of_measurement})'

class Tag(models.Model):
    """
    Информация о тэгах
    """
    name = models.CharField(max_length=10, null=False, verbose_name='Название')
    slug = models.SlugField(max_length=15, unique=True, null=False, verbose_name='slug')
    style = models.CharField(max_length=15, default='purple', verbose_name='Цвет оформления')

    def __str__(self):
        return self.name


class Recipes(models.Model):
    """
    Информация о рецептах
    """
    author = models.ForeignKey(User, on_delete=models.DO_NOTHING, verbose_name='Автор')
    name = models.CharField(max_length=200, unique=True, verbose_name='Название рецепта')
    image = models.ImageField(upload_to='irecipes/%d_%m_%Y/')
    description = models.CharField(max_length=1000, verbose_name='Описание ')
    ingredient_in = models.ManyToManyField('IngredientIncomposition',blank=False)
    tag = models.ManyToManyField('Tag')
    pub_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')
    time = models.PositiveSmallIntegerField(default=10, verbose_name='Время приготовления')

    def __str__(self):
        return self.name


class IngredientIncomposition(models.Model):
    """
    Информация о ингредиентах, входящих в рецепт
    """
    # recipe = models.ForeignKey(Recipes, on_delete=models.CASCADE, blank=True, null=False)
    ingredient = models.ForeignKey(Ingredient,on_delete=models.DO_NOTHING)
    quantity = models.SmallIntegerField(verbose_name='Количество')

    def __str__(self):
        return self.ingredient.name


class Follow(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE,
                             related_name="follower", verbose_name="Подписчик")
    author = models.ForeignKey(User, on_delete=models.CASCADE,
                               related_name="following", verbose_name="Автор постов")


class Favorite(models.Model):
    fuser = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="favorites_user", verbose_name="Пользователь")
    recipe = models.ForeignKey(
        Recipes, on_delete=models.CASCADE, related_name="favorite_recipe", verbose_name="Рецепт в избранном")


class ShoppingList(models.Model):
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="shoplist_user", verbose_name="Пользователь")
    recipe = models.ForeignKey(
        Recipes, on_delete=models.CASCADE, related_name="shoplist_recipe", verbose_name="Рецепт с продуктами для покупки")

the_end/templates/authorRecipe.html
{% extends "base.html" %}
{% load cache %}
{% load static %}


{% block title %} Авторские рецепты {% endblock %}


{% block static %}
    <link rel="stylesheet" href="./pages/index.css">
{% endblock %}


{% block content %}
    {% include "item/RecipeItem.html" %}
{% endblock %}


{% include "paginator.html"%}


{% block java-script %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/AuthorRecipe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/authorRecipe.js' %}"></script>
{% endblock %}

the_end/templates/base.html
<!doctype html>
{% load static %}
{% csrf_token %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Заголовок страницы{% endblock %}</title>
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">


    {% block static %}

    {% endblock %}

{% csrf_token %}
</head>

<body class="body">


    {% include 'nav.html'%}

    {% block content %}
            Контент
    {% endblock %}

    {% include 'paginator.html'%}


    {% include 'footer.html'%}

    {% block java-script %}

    {% endblock %}

</body>
</html>

the_end/templates/customPage.html
{% extends "base.html" %}
{% load cache %}
{% load static %}

{% block title %}  Регистрация {% endblock %}


{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}

{% block content %}
    <main class="main container">
    <div class="custom-center-block">
            <p class="custom-text-block">Сообщение пользователю</p>
        <div class="custom-button-block">
            <button class="button button_style_blue">Перейти на главную</button>
        </div>
    </div>
</main>
{% endblock %}

the_end/templates/favorite.html
{% extends "base.html" %}
{% load cache %}
{% load static %}

{% block title %}  Избранные рецепты {% endblock %}


{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}

{% block content %}
    {% include "item/RecipeItem.html" %}
{% endblock %}

{% block java-script %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/favorite.js' %}"></script>

{% endblock %}

the_end/templates/footer.html
<footer class="footer">
    <div class="footer__container container">
        <a href="{% url 'foodgram' %}" class="footer__brand link">Продуктовый помощник</a>
        <ul class="footer__items">
            <li class="footer__item"><a href="{% url 'about_me' %}" class="footer__link link">Об авторе </a></li>
            <li class="footer__item"><a href="{% url 'tech' %}" class="footer__link link">Технологии</a></li>
        </ul>
    </div>
</footer>

the_end/templates/formChangeRecipe.html
{% extends "base.html" %}
{% block title %} Создать рецепт {% endblock %}

{% block static %}
{% load static %}
{% load user_filters %}
{% csrf_token %}
    <link rel="stylesheet" href="{% static '/pages/form.css' %}">
{% endblock %}
{% block content %}
{% csrf_token %}
<main class="main container">
    {% csrf_token %}
    <div class="main__header">
        <h1 class="main__title">Редактирование рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="form__group">
                {% csrf_token %}
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input"
                    value="{{recipe.name}}">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="form__field-group">
                    <div class="tags">
                        {% for tag in tags %}
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="{{ tag.id }}" id="id_{{ tag.slug }}"
                                class="tags__checkbox tags__checkbox_style_{{ tag.style }}"
                                {% if tag in tags_list %} checked {% endif %}>

                            <label for="id_{{ tag.slug }}" class="tags__label">{{ tag.name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    <span class="form__error">{{ form.tags.errors|striptags }}</span>
                </div>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal">шт.</label>
                    </div>

                    <div class="form__field-group-ingredientes-container">
                        <div class="form__field-item-ingredient" id="ing_3">
                            <span> Оливки 10шт.</span>
                            <span class="form__field-item-delete"></span>
                            <input id="nameIngredient_3" name="nameIngredient_3" type="hidden" value="Оливки">
                            <input id="valueIngredient_3" name="valueIngredient_3" type="hidden" value="10">
                            <input id="unitsIngredient_3" name="unitsIngredient_3" type="hidden" value="шт.">
                        </div>
                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="time" class="form__input"
                    value="{{recipe.time}}">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8"
                        class="form__textarea">{{recipe.description|striptags|safe}}</textarea>
                    <span class="form__error">{{ form.description.errors|striptags }}</span>
                </div>
            </div>
            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    {% csrf_token %}
                    <label for="id_file" class="form__file-button">Выбрать файл</label>
                    <input type="file" class="form__file" name="file" id="id_file">
                    <span class="form__error"></span>
                </div>
            </div>
            {% if recipe.image != Null %}
            <div class="form__group">
                <span class="form__label">Текущее</span>
                <div class="form__field-group">
                    <img src="/media/{{ recipe.image }}" alt="" style="width:100px;">
                </div>
            </div>
            {% endif %}
            <div class="form__footer">
                {% csrf_token %}
                <button class="button button_style_blue">Сохранить</button> <a style="margin-left: 2.5em" href="#" class="form__ingredient-link">Удалить</a>
            </div>

        </form>
    </div>


</main>



{% endblock %}

{% block java-script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static '/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/formRecipe.js' %}"></script>
{% endblock %}

the_end/templates/formRecipe.html
{% extends "base.html" %}
{% block title %} Создать рецепт {% endblock %}


{% block static %}
{% load static %}
{% load user_filters %}
{% csrf_token %}
    <link rel="stylesheet" href="{% static '/pages/form.css' %}">
{% endblock %}
{% block content %}
{% csrf_token %}
<main class="main container" >
    <div class="main__header">
        <h1 class="main__title">Создание рецепта</h1>
    </div>
    <div class="form-container">
        <form class="form" method="post" enctype="multipart/form-data">
            <div class="form__group">
                <label for="id_name" class="form__label">Название рецепта</label>
                <div class="form__field-group">
                    <input type="text" id="id_name" name="name" class="form__input">
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                {% csrf_token %}
                <p class="form__label">Теги</p>
                <div class="form__field-group">
                    <div class="tags">
                        {% for tag in tags %}
                        <div class="tags__item">
                            <input type="checkbox" name="tags" value="{{ tag.id }}" id="id_{{ tag.slug }}"
                                class="tags__checkbox tags__checkbox_style_{{ tag.style }}"
                                {% if tag.slug in list_tags %} checked {% endif %}>

                            <label for="id_{{ tag.slug }}" class="tags__label">{{ tag.name }}</label>
                        </div>
                        {% endfor %}
                    </div>
                    <span class="form__error">{{ form.tags.errors|striptags }}</span>
                </div>

            </div>
            <div class="form__group">
                {% csrf_token %}
                <label for="nameIngredient" class="form__label">Ингредиенты</label>
                <div class="form__field-group">
                    <div class="form__field-group-ingredientes">
                        <div class="form__dropdown">
                            <input type="text" id="nameIngredient" class="form__input">
                            <div class="form__dropdown-items"></div>
                        </div>
                        <input type="number" id="cantidad" class="form__input" min="0">
                        <label for="cantidad" class="form__label" id="cantidadVal"> шт.</label>
                    </div>
                    <div class="form__field-group-ingredientes-container">

                    </div>
                    <span class="form__ingredient-link" id="addIng">Добавить ингредиент</span>
                    <span class="form__error"></span>
                </div>
            </div>
            <div class="form__group">
                <label for="id_time" class="form__label">Время приготовления</label>
                <div class="form__field-group form__field-group_time">
                    <input type="text" id="id_time" name="time" class="form__input"
                        value="{{recipe.time}}">
                    <label for="id_time" class="form__label">минут</label>
                    <span class="form__error"> {{ form.time.error|striptags }}</span>

                </div>
            </div>

            <div class="form__group">
                <label for="id_description" class="form__label">Описание</label>
                <div class="form__field-group">
                    <textarea name="description" id="id_description" rows="8"
                        class="form__textarea">{{recipe.description|striptags|safe}}</textarea>
                    <span class="form__error">{{ form.description.errors|striptags }}</span>
                </div>
            </div>

            <div class="form__group">
                <span class="form__label">Загрузить фото</span>
                <div class="form__field-group">
                    <input type="file" name="image" id="id_file" value="">
                    <span class="form__error">{{ form.image.error|striptags }}</span>
                </div>

            </div>
            <div class="form__footer">
                <button class="button button_style_blue">Создать рецепт</button>
            </div>
        </form>
    </div>


</main>


{% endblock %}

{% block java-script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static '/js/utils/debouncing.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/formRecipe.js' %}"></script>
{% endblock %}

the_end/templates/indexAuth.html
{% extends "base.html" %}

{% load static %}
{% csrf_token %}
{% block title %}  Последние рецепты {% endblock %}


{% block static %}
    <link rel="stylesheet" href="{% static '/pages/index.css' %}">
{% endblock %}

{% block content %}
    {% include "item/RecipeItem.html" %}


{% endblock %}

{% block java-script %}
{% csrf_token %}
    <script src="{% static 'js/components/MainCards.js' %}"></script>

    <script src="{% static 'js/components/Purchases.js' %}"></script>
    <script src="{% static 'js/components/Favorites.js' %}"></script>

    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/CardList.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>

    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/indexAuth.js' %}"></script>

{% endblock %}

the_end/templates/myFollow.html
{% extends "base.html" %}
{%load cache%}
{% load static %}
{% block title %} Мои подписки {% endblock %}



{% block static %}
   <link rel="stylesheet" href="{% static 'pages/myFollow.css' %}">
{% endblock %}

{% block content %}
{% load v1_filters %}
    <main class="main container">
    <div class="main__header">
        <h1 class="main__title">Мои подписки</h1>
    </div>
    <div class="card-list">
        {% for follow in follow%}
            <div class="card-user" data-author="{{follow.author.id}}">
        <div class="card-user__header">
            <h2 class="card-user__title">{{follow.author.username}}</h2>
        </div>
        <div class="card-user__body">
            <ul class="card-user__items">
                {% for recipe in request|items_follow:follow.author.id|slice:":3" %}
                    <li class="card-user__item">
                    <div class="recipe">
                        {% load thumbnail %}
                        {% thumbnail recipe.image "72x72" as im %}
                        <img src="{{ im.url }}" class="recipe__image">
                        {% endthumbnail %}
                        <h3 class="recipe__title">{{recipe.name}}</h3>
                        <p class="recipe__text"><span class="icon-time"></span> {{recipe.time}} мин.</p>
                    </div>
                </li>

                {% endfor %}
                {% if request|count_recipises:follow.author.id > 0 %}
                <li class="card-user__item">
                    <a href="{% url 'author' user_id=follow.author.id %}" class="card-user__link link">Еще
                    {{ request|count_recipises:follow.author.id }} рецептов</a>
                {% endif %}
            </ul>
        </div>
        <div class="card-user__footer">
            <button class="button button_style_light-blue button_size_auto" name="subscribe">Отписаться</button>
        </div>
    </div>
        {% endfor %}
    </div>
</main>
{% endblock %}

{% block java-script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/MainCards.js' %}"></script>
    <script src="{% static 'js/components/MyFollow.js' %}"></script>
    <script src="{% static 'js/components/Subscribe.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/myFollow.js' %}"></script>

{% endblock %}

the_end/templates/nav.html
{% load v1_filters %}
<header class="header">
      <nav class="nav">
          {% if user.is_authenticated %}
          <div class="nav__container container">

                <ul class="nav__items list">
                    <li class="nav__item"><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                    <li class="nav__item"><a href="{% url 'follow_index' %}" class="nav__link link">Мои подписки</a></li>
                    <li class="nav__item"><a href="{% url 'recipe_new' %}" class="nav__link link">Создать рецепт</a></li>
                    <li class="nav__item"><a href="{% url 'favorites' %}" class="nav__link link">Избранное</a></li>
                    <li class="nav__item"><a href="{% url 'shopping-list' %}" class="nav__link link">Список покупок</a>
                        <span class="badge badge_style_blue nav__badge" id="counter">{{ request|count_shoplist }}</span></li>

                </ul>
              <ul class="nav__items list">
                  <li class="nav__item"><a href="{% url 'password_change' %}" class="nav__link link">Изменить пароль</a></li>
                  <li class="nav__item"><a href="{% url 'logout' %}" class="nav__link link">Выход</a></li>
          {% else %}
          <div class="nav__container container">
                    <ul class="nav__items list">
                        <li class="nav__item "><a href="{% url 'index' %}" class="nav__link link">Рецепты</a></li>
                        <li class="nav__item"><a href="{% url 'login' %}" class="nav__link link">Войти</a></li>
                        <li class="nav__item"><a href="{% url 'signup' %}" class="nav__link link">Создать аккаунт</a></li>
                    </ul>

          </div>
          {% endif %}
      </nav>
</header>

the_end/templates/paginator.html
<nav class="pagination" aria-label="Search results pages">
            <ul class="pagination__container">
                <li class="pagination__item"><a class="pagination__link link" href=><span class="icon-left"></span></a></li>
                {% for i in paginator.page_range %}
                    {% if items.number == i %}
                        <li class="page-item active"><span class="page-link">{{i}}<span class="sr-only"> (текущая) </span></span></li>
                    {% else %}
                        <li class="page-item"><a class="page-link" href="?page={{ i }}"> {{i}} </a></li>
                    {% endif %}
                {% endfor %}
            </ul>
</nav >

the_end/templates/shopping-list.html
{% extends 'base.html' %}
{% block title%} Список покупок {% endblock%}
{% block shop %} <li class="nav__item nav__item_active"> {% endblock %}
{% load static %}
    {% csrf_token %}
    {% block static %}
    <link rel="stylesheet" href="{% static '/pages/shopList.css' %}">
    {% endblock %}
    {% load user_filters %}
    {% block content %}


<main class="main container">
    <div class="main__header">
        <h1 class="main__title">Список покупок</h1>
    </div>
    <div class="card-list card-list_column">
        <ul class="shopping-list">
            {% for recipe in shopping_list %}
            <li class="shopping-list__item" data-id="{{ recipe.recipe.id }}">
                <div class="recipe recipe_reverse">
                    <img src="{{ recipe.recipe.image.url }}" alt="{{ recipe.recipe.name }}" class="recipe__image recipe__image_big">
                    <h3 class="recipe__title">{{ recipe.recipe.name }}</h3>
                    <p class="recipe__text"><span class="icon-time"></span> {{ recipe.recipe.time }} мин.</p>
                </div>
                <a  class="shopping-list__button link">Удалить</a>
            </li>
            {% endfor %}
        </ul>
        <a href="#"> Скачать список </a>


    </div>
</main>

{% endblock %}
    {% block java-script %}
    <script src="{% static 'js/config/config.js' %}"></script>
    <script src="{% static 'js/components/Header.js' %}"></script>
    <script src="{% static 'js/components/ShopList.js' %}"></script>
    <script src="{% static 'js/api/Api.js' %}"></script>
    <script src="{% static 'js/pages/shopList.js' %}"></script>
    {% endblock %}